package visao;

import javax.swing.JFrame;
import modelo.Produto;
import modelo.dao.ProdutoDao;

public class FrmGerenciarProduto extends javax.swing.JFrame {

    public FrmGerenciarProduto() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTableProdutos = new javax.swing.JTable();
        JLNome = new javax.swing.JLabel();
        JLPrecoUnitario = new javax.swing.JLabel();
        JLUnidade = new javax.swing.JLabel();
        JLQtdEstoque = new javax.swing.JLabel();
        JLQtdMinima = new javax.swing.JLabel();
        JLQtdMaxima = new javax.swing.JLabel();
        JLGerenciamentoProdutos = new javax.swing.JLabel();
        JTFnome = new javax.swing.JTextField();
        JTFprecoUnitario = new javax.swing.JTextField();
        JTFunidade = new javax.swing.JTextField();
        JTFqtdEstoque = new javax.swing.JTextField();
        JTFqtdMinima = new javax.swing.JTextField();
        JTFqtdMaxima = new javax.swing.JTextField();
        JBNovo = new javax.swing.JButton();
        JBAlterar = new javax.swing.JButton();
        JBExcluir = new javax.swing.JButton();
        JBVoltarGerenciamentoP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Produtos");

        JTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Preço", "Quantidade", "QtdMinima", "QtdMaxima", "Categoria"
            }
        ));
        JTableProdutos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(JTableProdutos);

        JLNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLNome.setText("Nome");

        JLPrecoUnitario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLPrecoUnitario.setText("Preço Unitário");

        JLUnidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLUnidade.setText("Unidade");

        JLQtdEstoque.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLQtdEstoque.setText("Qtd. em Estoque");

        JLQtdMinima.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLQtdMinima.setText("Qtd. Mínima");

        JLQtdMaxima.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLQtdMaxima.setText("Qtd. Máxima");

        JLGerenciamentoProdutos.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        JLGerenciamentoProdutos.setText("Gerenciamento de Produtos");

        JTFnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFnomeActionPerformed(evt);
            }
        });

        JTFprecoUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFprecoUnitarioActionPerformed(evt);
            }
        });

        JTFunidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFunidadeActionPerformed(evt);
            }
        });

        JBNovo.setText("Novo");
        JBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNovoActionPerformed(evt);
            }
        });

        JBAlterar.setText("Alterar");

        JBExcluir.setText("Excluir");

        JBVoltarGerenciamentoP.setText("Voltar");
        JBVoltarGerenciamentoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVoltarGerenciamentoPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLPrecoUnitario)
                    .addComponent(JLNome)
                    .addComponent(JLUnidade)
                    .addComponent(JLQtdEstoque)
                    .addComponent(JLQtdMinima)
                    .addComponent(JLQtdMaxima))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JTFprecoUnitario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTFunidade, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTFqtdEstoque, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTFqtdMinima, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTFqtdMaxima, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(JTFnome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBVoltarGerenciamentoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(JLGerenciamentoProdutos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JLNome, JLPrecoUnitario, JLQtdEstoque, JLQtdMaxima, JLQtdMinima, JLUnidade});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(JLGerenciamentoProdutos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JLNome)
                                    .addComponent(JTFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JTFprecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLPrecoUnitario))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JTFunidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLUnidade))
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBNovo)
                                .addGap(20, 20, 20)
                                .addComponent(JBAlterar)
                                .addGap(20, 20, 20)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLQtdEstoque)
                            .addComponent(JTFqtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFqtdMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLQtdMinima))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFqtdMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLQtdMaxima)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBExcluir)
                        .addGap(20, 20, 20)
                        .addComponent(JBVoltarGerenciamentoP)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBVoltarGerenciamentoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVoltarGerenciamentoPActionPerformed
        // TODO add your handling code here:
        FrmMenuPrincipal janela = new FrmMenuPrincipal();
        janela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBVoltarGerenciamentoPActionPerformed

    private void JBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNovoActionPerformed

    }//GEN-LAST:event_JBNovoActionPerformed

    private void JTFnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFnomeActionPerformed

    private void JTFprecoUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFprecoUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFprecoUnitarioActionPerformed

    private void JTFunidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFunidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFunidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAlterar;
    private javax.swing.JButton JBExcluir;
    private javax.swing.JButton JBNovo;
    private javax.swing.JButton JBVoltarGerenciamentoP;
    private javax.swing.JLabel JLGerenciamentoProdutos;
    private javax.swing.JLabel JLNome;
    private javax.swing.JLabel JLPrecoUnitario;
    private javax.swing.JLabel JLQtdEstoque;
    private javax.swing.JLabel JLQtdMaxima;
    private javax.swing.JLabel JLQtdMinima;
    private javax.swing.JLabel JLUnidade;
    private javax.swing.JTextField JTFnome;
    private javax.swing.JTextField JTFprecoUnitario;
    private javax.swing.JTextField JTFqtdEstoque;
    private javax.swing.JTextField JTFqtdMaxima;
    private javax.swing.JTextField JTFqtdMinima;
    private javax.swing.JTextField JTFunidade;
    private javax.swing.JTable JTableProdutos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
