package visao;

import controlador.ProdutoControle;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JFrame;
import modelo.dao.db.DbException;

public class FrmReajustarPreco extends javax.swing.JFrame {

    public FrmReajustarPreco() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLAumentarPreço = new javax.swing.JLabel();
        JLReajuste = new javax.swing.JLabel();
        JTFAumentarPorcentagem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JBVoltar = new javax.swing.JButton();
        jBAumentarPreco = new javax.swing.JButton();
        jBDiminuirPreco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reajustar Preços");

        JLAumentarPreço.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JLAumentarPreço.setText("Aumentar os preços em %");

        JLReajuste.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        JLReajuste.setText("Reajuste de Preços");

        jLabel3.setText("%");

        JBVoltar.setText("Voltar");
        JBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVoltarActionPerformed(evt);
            }
        });

        jBAumentarPreco.setText("Aumentar");
        jBAumentarPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAumentarPrecoActionPerformed(evt);
            }
        });

        jBDiminuirPreco.setText("Diminuir");
        jBDiminuirPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDiminuirPrecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTFAumentarPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3)
                            .addGap(83, 83, 83))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JLReajuste)
                                .addComponent(JLAumentarPreço))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(JBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBAumentarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBDiminuirPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(JLReajuste)
                .addGap(40, 40, 40)
                .addComponent(JLAumentarPreço)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFAumentarPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAumentarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDiminuirPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVoltarActionPerformed
        FrmMenuPrincipal janela = new FrmMenuPrincipal();
        janela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBVoltarActionPerformed

    private void jBAumentarPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAumentarPrecoActionPerformed
        try {
            double percentual = Double.parseDouble(JTFAumentarPorcentagem.getText());
            if (percentual <= 0) {
                return;
            }

            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/trabalhoa3?useSSL=false&serverTimezone=UTC", "root", "1234567");
            ProdutoControle controle = new ProdutoControle(conn);
            controle.aumentarTodosPrecos(percentual);
            conn.close();

        } catch (NumberFormatException e) {
            throw new DbException(e.getMessage());
        } catch (SQLException e) {
            throw new DbException(e.getMessage());
        }
     }//GEN-LAST:event_jBAumentarPrecoActionPerformed

    private void jBDiminuirPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDiminuirPrecoActionPerformed
        try {
            double percentual = Double.parseDouble(JTFAumentarPorcentagem.getText());
            if (percentual <= 0) {
                return;
            }

            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/trabalhoa3?useSSL=false&serverTimezone=UTC", "root", "1234567");
            ProdutoControle controle = new ProdutoControle(conn);
            controle.diminuirTodosPrecos(percentual);
            conn.close();

        } catch (NumberFormatException e) {
            throw new DbException(e.getMessage());
        } catch (SQLException e) {
            throw new DbException(e.getMessage());
        }
    }//GEN-LAST:event_jBDiminuirPrecoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBVoltar;
    private javax.swing.JLabel JLAumentarPreço;
    private javax.swing.JLabel JLReajuste;
    private javax.swing.JTextField JTFAumentarPorcentagem;
    private javax.swing.JButton jBAumentarPreco;
    private javax.swing.JButton jBDiminuirPreco;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
