package view;

/**
 *
 * @author Andradevh
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLMenuPrincipal = new javax.swing.JLabel();
        JBGerenciarCategorias = new javax.swing.JButton();
        JBReajustarPrecos = new javax.swing.JButton();
        JBSair = new javax.swing.JButton();
        JBGerenciarProdutos = new javax.swing.JButton();
        JBMovimentarEstoque = new javax.swing.JButton();
        JBEmitirRelatorios = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuGerenciarProdutos = new javax.swing.JMenuItem();
        jMenuGerenciarCategorias = new javax.swing.JMenuItem();
        jMenuMovimentarEstoque = new javax.swing.JMenuItem();
        jMenuReajustarPrecos = new javax.swing.JMenuItem();
        jMenuEmitirRelatorios = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de Estoque - Menu Principal");

        JLMenuPrincipal.setBackground(new java.awt.Color(153, 153, 153));
        JLMenuPrincipal.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        JLMenuPrincipal.setText("Menu Principal");
        JLMenuPrincipal.setAlignmentY(0.0F);

        JBGerenciarCategorias.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBGerenciarCategorias.setText("Gerenciar Categorias");
        JBGerenciarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGerenciarCategoriasActionPerformed(evt);
            }
        });

        JBReajustarPrecos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBReajustarPrecos.setText("Reajustar Preços");

        JBSair.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBSair.setText("Sair");
        JBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSairActionPerformed(evt);
            }
        });

        JBGerenciarProdutos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBGerenciarProdutos.setText("Gerenciar Produtos");
        JBGerenciarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGerenciarProdutosActionPerformed(evt);
            }
        });

        JBMovimentarEstoque.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBMovimentarEstoque.setText("Movimentar Estoque");
        JBMovimentarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMovimentarEstoqueActionPerformed(evt);
            }
        });

        JBEmitirRelatorios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBEmitirRelatorios.setText("Emitir Relatórios");
        JBEmitirRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEmitirRelatoriosActionPerformed(evt);
            }
        });

        jMenuBar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jMenuArquivo.setText("Arquivo");

        jMenuGerenciarProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, 0));
        jMenuGerenciarProdutos.setText("Gerenciar Produtos");
        jMenuGerenciarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGerenciarProdutosActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuGerenciarProdutos);

        jMenuGerenciarCategorias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, 0));
        jMenuGerenciarCategorias.setText("Gerenciar Categorias");
        jMenuGerenciarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGerenciarCategoriasActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuGerenciarCategorias);

        jMenuMovimentarEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, 0));
        jMenuMovimentarEstoque.setText("Movimentar Estoque");
        jMenuMovimentarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMovimentarEstoqueActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuMovimentarEstoque);

        jMenuReajustarPrecos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, 0));
        jMenuReajustarPrecos.setText("Reajustar Preços");
        jMenuArquivo.add(jMenuReajustarPrecos);

        jMenuEmitirRelatorios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, 0));
        jMenuEmitirRelatorios.setText("Emitir Relatórios");
        jMenuArquivo.add(jMenuEmitirRelatorios);

        jMenuBar.add(jMenuArquivo);

        jMenuSobre.setText("Sobre");
        jMenuBar.add(jMenuSobre);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JBMovimentarEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBGerenciarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBEmitirRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBGerenciarCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBReajustarPrecos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(JLMenuPrincipal)))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(JLMenuPrincipal)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBGerenciarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBGerenciarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBMovimentarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBReajustarPrecos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBEmitirRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBSairActionPerformed

    private void JBGerenciarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGerenciarProdutosActionPerformed
        FrmGerenciarProdutos janela = new FrmGerenciarProdutos();
        janela.setVisible(true);
    }//GEN-LAST:event_JBGerenciarProdutosActionPerformed

    private void JBMovimentarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMovimentarEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBMovimentarEstoqueActionPerformed

    private void JBEmitirRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEmitirRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBEmitirRelatoriosActionPerformed

    private void JBGerenciarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGerenciarCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBGerenciarCategoriasActionPerformed

    private void jMenuMovimentarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMovimentarEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuMovimentarEstoqueActionPerformed

    private void jMenuGerenciarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGerenciarCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuGerenciarCategoriasActionPerformed

    private void jMenuGerenciarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGerenciarProdutosActionPerformed
        // Instancia a tela de cadastro de aluno
        FrmGerenciarProdutos objeto = new FrmGerenciarProdutos();
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuGerenciarProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBEmitirRelatorios;
    private javax.swing.JButton JBGerenciarCategorias;
    private javax.swing.JButton JBGerenciarProdutos;
    private javax.swing.JButton JBMovimentarEstoque;
    private javax.swing.JButton JBReajustarPrecos;
    private javax.swing.JButton JBSair;
    private javax.swing.JLabel JLMenuPrincipal;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuEmitirRelatorios;
    private javax.swing.JMenuItem jMenuGerenciarCategorias;
    private javax.swing.JMenuItem jMenuGerenciarProdutos;
    private javax.swing.JMenuItem jMenuMovimentarEstoque;
    private javax.swing.JMenuItem jMenuReajustarPrecos;
    private javax.swing.JMenu jMenuSobre;
    // End of variables declaration//GEN-END:variables
}
